version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL = http://localhost:3001
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_CONNECTION=mongodb://mongodb/todo-app
      - PORT=3001
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - todo-app:/data/db
    ports:
      - "27018:27017"
volumes:
  todo-app:
